package workflow

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/tarikogut/ai-callcenter-orchestrator/pkg/diameter"
)

// KamailioInboundSMS represents payload sent by Kamailio SMS-IWF to orchestrator webhook
type KamailioInboundSMS struct {
	SMSCID    string `json:"smsc_id"`    // Source SMSC ID (e.g. "sim1", "carrier_fast")
	From      string `json:"from"`       // Sender phone number
	To        string `json:"to"`         // Destination DID / Shortcode
	Text      string `json:"text"`       // Inbound SMS text
	Timestamp string `json:"timestamp"`  // Timestamp string
	TenantID  string `json:"tenant_id"`  // Tenant if pre-classified
	MsgID     string `json:"msg_id"`     // Kamailio message ID
}

// KamailioOutboundSMS represents payload needed to send SMS back via Kamailio SMS-IWF REST API
type KamailioOutboundSMS struct {
	SMSCID string `json:"smsc_id"`
	From   string `json:"from"`
	To     string `json:"to"`
	Text   string `json:"text"`
}

// SmsWorkflowResolver resolves SMS workflow for tenant or destination number
type SmsWorkflowResolver func(tenantID, did string) (*WorkflowDefinition, error)

// SmsSender defines interface or callback to dispatch outbound SMS back to Kamailio SMS-IWF
type SmsSender interface {
	SendSMS(ctx context.Context, outbound KamailioOutboundSMS) error
}

// HTTPKamailioSmsSender dispatches SMS to Kamailio SMS-IWF POST /api/v1/sms/send
type HTTPKamailioSmsSender struct {
	Endpoint   string // e.g. "http://127.0.0.1:8080/api/v1/sms/send"
	AuthBearer string
	Client     *http.Client
}

func NewHTTPKamailioSmsSender(endpoint, token string) *HTTPKamailioSmsSender {
	return &HTTPKamailioSmsSender{
		Endpoint:   endpoint,
		AuthBearer: token,
		Client: &http.Client{
			Timeout: 5 * time.Second,
		},
	}
}

func (s *HTTPKamailioSmsSender) SendSMS(ctx context.Context, outbound KamailioOutboundSMS) error {
	data, err := json.Marshal(outbound)
	if err != nil {
		return err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, s.Endpoint, bytes.NewReader(data))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	if s.AuthBearer != "" {
		req.Header.Set("Authorization", "Bearer "+s.AuthBearer)
	}

	resp, err := s.Client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to dispatch SMS to Kamailio: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("kamailio responded with status %d: %s", resp.StatusCode, string(body))
	}

	return nil
}

// SmsHandler handles inbound SMS from Kamailio SMS-IWF, runs matching workflow and sends reply
type SmsHandler struct {
	engine           *Engine
	diamClient       diameter.RoClient
	workflowResolver SmsWorkflowResolver
	smsSender        SmsSender

	mu        sync.RWMutex
	history   []*ExecutionContext
	lastReply string
}

// NewSmsHandler creates an SmsHandler instance
func NewSmsHandler(engine *Engine, diamClient diameter.RoClient, resolver SmsWorkflowResolver, sender SmsSender) *SmsHandler {
	return &SmsHandler{
		engine:           engine,
		diamClient:       diamClient,
		workflowResolver: resolver,
		smsSender:        sender,
		history:          make([]*ExecutionContext, 0),
	}
}

// HandleInboundSMS processes an inbound SMS message
func (h *SmsHandler) HandleInboundSMS(ctx context.Context, req KamailioInboundSMS) (*ExecutionContext, error) {
	if req.From == "" || req.To == "" {
		return nil, errors.New("sms 'from' and 'to' fields are required")
	}

	tenantID := req.TenantID
	if tenantID == "" {
		tenantID = "default_tenant"
	}

	sessionID := fmt.Sprintf("sms-%s-%d", req.MsgID, time.Now().UnixNano())
	if req.MsgID == "" {
		sessionID = fmt.Sprintf("sms-%s-%d", req.From, time.Now().UnixNano())
	}

	execCtx := NewExecutionContext(
		tenantID,
		"",
		sessionID,
		TriggerTypeSms,
		req.From,
		req.To,
	)
	execCtx.SmsInboundText = req.Text
	execCtx.SetVariable("$sms_inbound_text", req.Text)

	// Resolve SMS workflow
	wf, err := h.workflowResolver(tenantID, req.To)
	if err != nil {
		return nil, fmt.Errorf("unable to resolve SMS workflow for %s: %w", req.To, err)
	}

	// Execute workflow
	err = h.engine.Execute(ctx, wf, execCtx)
	if err != nil {
		return execCtx, fmt.Errorf("workflow execution failed: %w", err)
	}

	// Dispatch outbound reply if generated by SmsReplyNode or flow
	if execCtx.SmsReplyText != "" && h.smsSender != nil {
		outbound := KamailioOutboundSMS{
			SMSCID: req.SMSCID,
			From:   req.To,   // Reply comes from the DID / shortcode
			To:     req.From, // Sent back to caller / originator
			Text:   execCtx.SmsReplyText,
		}
		if outbound.SMSCID == "" {
			outbound.SMSCID = "sim1"
		}

		if sendErr := h.smsSender.SendSMS(ctx, outbound); sendErr != nil {
			return execCtx, fmt.Errorf("reply SMS dispatch failed: %w", sendErr)
		}
	}

	h.mu.Lock()
	h.lastReply = execCtx.SmsReplyText
	h.history = append(h.history, execCtx)
	h.mu.Unlock()

	return execCtx, nil
}

// WebhookHandler provides an http.HandlerFunc matching `POST /api/v1/webhook/sms`
func (h *SmsHandler) WebhookHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var payload KamailioInboundSMS
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			http.Error(w, "invalid json payload: "+err.Error(), http.StatusBadRequest)
			return
		}

		execCtx, err := h.HandleInboundSMS(r.Context(), payload)
		if err != nil {
			http.Error(w, "workflow processing error: "+err.Error(), http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]interface{}{
			"status":     "ok",
			"session_id": execCtx.SessionID,
			"reply":      execCtx.SmsReplyText,
			"variables":  execCtx.Variables,
		})
	}
}
