import {
  Tenant,
  DIDNumber,
  DiameterMetric,
  Extension,
  AiPersonaConfig,
  McpServerConfig,
  FaqItem,
  CdrRecord,
  LiveTranscriptEntry,
} from '../types';

export const initialTenants: Tenant[] = [
  {
    id: 'eczane_hayat',
    name: 'Hayat Eczanesi & Nöbet Hattı',
    domain: 'hayateczanesi.com',
    industry: 'pharmacy',
    status: 'active',
    balance: 840.50,
    currency: 'TRY',
    maxConcurrentCalls: 10,
    monthlySpendLimit: 5000,
    currentConcurrentCalls: 3,
    assignedDids: ['+90 850 111 0001', '+90 216 450 1234'],
    createdAt: '2026-01-15',
    contactEmail: 'iletisim@hayateczanesi.com',
  },
  {
    id: 'jet_kargo',
    name: 'Jet Kargo Express Dağıtım',
    domain: 'jetkargo.com.tr',
    industry: 'logistics',
    status: 'active',
    balance: 2150.00,
    currency: 'TRY',
    maxConcurrentCalls: 30,
    monthlySpendLimit: 15000,
    currentConcurrentCalls: 8,
    assignedDids: ['+90 850 222 3456'],
    createdAt: '2026-02-01',
    contactEmail: 'operasyon@jetkargo.com.tr',
  },
  {
    id: 'acibadem_dent',
    name: 'DentCare Ağız ve Diş Sağlığı',
    domain: 'dentcare.com.tr',
    industry: 'clinic',
    status: 'active',
    balance: 320.00,
    currency: 'TRY',
    maxConcurrentCalls: 5,
    monthlySpendLimit: 3000,
    currentConcurrentCalls: 1,
    assignedDids: ['+90 850 333 7890'],
    createdAt: '2026-03-10',
    contactEmail: 'randevu@dentcare.com.tr',
  },
  {
    id: 'mega_store',
    name: 'Mega Store E-Ticaret',
    domain: 'megastore.com.tr',
    industry: 'ecommerce',
    status: 'frozen',
    balance: 12.40,
    currency: 'TRY',
    maxConcurrentCalls: 15,
    monthlySpendLimit: 8000,
    currentConcurrentCalls: 0,
    assignedDids: ['+90 212 900 1234'],
    createdAt: '2025-11-20',
    contactEmail: 'destek@megastore.com.tr',
  },
];

export const initialDids: DIDNumber[] = [
  {
    id: 'did_1',
    number: '+90 850 111 0001',
    countryCode: 'TR',
    carrier: 'Turkcell Superonline SIP Trunk',
    tenantId: 'eczane_hayat',
    tenantName: 'Hayat Eczanesi & Nöbet Hattı',
    assignedAt: '2026-01-15',
    status: 'assigned',
    monthlyCost: 45.00,
  },
  {
    id: 'did_2',
    number: '+90 216 450 1234',
    countryCode: 'TR',
    carrier: 'Türk Telekom PSTN Interconnect',
    tenantId: 'eczane_hayat',
    tenantName: 'Hayat Eczanesi & Nöbet Hattı',
    assignedAt: '2026-02-10',
    status: 'assigned',
    monthlyCost: 55.00,
  },
  {
    id: 'did_3',
    number: '+90 850 222 3456',
    countryCode: 'TR',
    carrier: 'Vodafone Carrier SIP',
    tenantId: 'jet_kargo',
    tenantName: 'Jet Kargo Express Dağıtım',
    assignedAt: '2026-02-01',
    status: 'assigned',
    monthlyCost: 45.00,
  },
  {
    id: 'did_4',
    number: '+90 850 333 7890',
    countryCode: 'TR',
    carrier: 'Turkcell Superonline SIP Trunk',
    tenantId: 'acibadem_dent',
    tenantName: 'DentCare Ağız ve Diş Sağlığı',
    assignedAt: '2026-03-10',
    status: 'assigned',
    monthlyCost: 45.00,
  },
  {
    id: 'did_5',
    number: '+90 212 900 1234',
    countryCode: 'TR',
    carrier: 'Türk Telekom PSTN Interconnect',
    tenantId: 'mega_store',
    tenantName: 'Mega Store E-Ticaret',
    assignedAt: '2025-11-20',
    status: 'assigned',
    monthlyCost: 55.00,
  },
  {
    id: 'did_6',
    number: '+90 850 555 9900',
    countryCode: 'TR',
    carrier: 'Verimor Telekom Cloud Trunk',
    tenantId: null,
    tenantName: null,
    assignedAt: null,
    status: 'available',
    monthlyCost: 40.00,
  },
  {
    id: 'did_7',
    number: '+90 850 777 4411',
    countryCode: 'TR',
    carrier: 'Netgsm SIP Gateway',
    tenantId: null,
    tenantName: null,
    assignedAt: null,
    status: 'available',
    monthlyCost: 40.00,
  },
  {
    id: 'did_8',
    number: '+90 312 800 5678',
    countryCode: 'TR',
    carrier: 'Türk Telekom PSTN Interconnect',
    tenantId: null,
    tenantName: null,
    assignedAt: null,
    status: 'available',
    monthlyCost: 55.00,
  },
];

export const initialDiameterMetric: DiameterMetric = {
  activeSessions: 12,
  ccrTotalCount: 48920,
  ccaSuccessRate: 99.98,
  avgRatingLatencyMs: 4.2,
  globalCdrToday: 1420,
  billedAmountToday: 3840.65,
  currency: 'TRY',
};

export const initialExtensions: Record<string, Extension[]> = {
  eczane_hayat: [
    {
      id: 'ext_101',
      extensionNumber: '101',
      name: 'Eczacı Danışma Masası',
      tenantId: 'eczane_hayat',
      sipUsername: '101_eczane',
      sipSecret: 'P@ssw0rd101',
      webrtcEnabled: true,
      status: 'online',
      assignedAgent: 'Eczacı Mehmet Bey',
    },
    {
      id: 'ext_102',
      extensionNumber: '102',
      name: 'Nöbetçi Asistan & Depo',
      tenantId: 'eczane_hayat',
      sipUsername: '102_eczane',
      sipSecret: 'P@ssw0rd102',
      webrtcEnabled: true,
      status: 'busy',
      assignedAgent: 'Asistan Selin',
    },
    {
      id: 'ext_103',
      extensionNumber: '103',
      name: 'Kurye & Eve Teslimat',
      tenantId: 'eczane_hayat',
      sipUsername: '103_eczane',
      sipSecret: 'P@ssw0rd103',
      webrtcEnabled: false,
      status: 'offline',
      assignedAgent: 'Motorlu Kurye Ali',
    },
  ],
  jet_kargo: [
    {
      id: 'ext_201',
      extensionNumber: '201',
      name: 'Müşteri Hizmetleri 1',
      tenantId: 'jet_kargo',
      sipUsername: '201_jet',
      sipSecret: 'P@ss201Jet',
      webrtcEnabled: true,
      status: 'online',
      assignedAgent: 'Temsilci Caner',
    },
    {
      id: 'ext_202',
      extensionNumber: '202',
      name: 'Dağıtım Şube Sorumlusu',
      tenantId: 'jet_kargo',
      sipUsername: '202_jet',
      sipSecret: 'P@ss202Jet',
      webrtcEnabled: true,
      status: 'online',
      assignedAgent: 'Sorumlu Emre',
    },
  ],
  acibadem_dent: [
    {
      id: 'ext_301',
      extensionNumber: '301',
      name: 'Klinik Sekreterliği',
      tenantId: 'acibadem_dent',
      sipUsername: '301_dent',
      sipSecret: 'DentP@ss301',
      webrtcEnabled: true,
      status: 'online',
      assignedAgent: 'Sekreter Merve',
    },
  ],
};

export const initialAiPersonas: Record<string, AiPersonaConfig> = {
  eczane_hayat: {
    agentName: 'Ayşe (Eczacı Asistanı)',
    voiceModel: 'gemini-live-aoede-warm',
    provider: 'gemini',
    tone: 'warm_empathic',
    systemPrompt: `Sen Hayat Eczanesi'nin sıcak kanlı, yardımsever ve dikkatli sanal yapay zeka asistanı Ayşe'sin.
Gelen hastaları güler yüzle karşıla ("Hayat Eczanesi'ne hoş geldiniz, ben Ayşe. Size nasıl yardımcı olabilirim?").
İlaç veya stok sorulduğunda doğrudan stok MCP aracını (check_medicine_stock) çalıştır.
Reçeteli ilaçlar hakkında doz tavsiyesi veremeyeceğini, gerekirse Eczacı Mehmet Bey'e (Dahili 101) aktaracağını nazikçe belirt.
Nöbetçi eczane ve adres sorularına net cevap ver.`,
    fillerPhrases: [
      'Hemen stoklarımızı kontrol ediyorum...',
      'Bir saniye sistemimize göz atıyorum...',
      'Hemen bakıyorum efendim...',
      'Reçete sistemine bağlanıyorum...',
    ],
    byokKey: 'AIzaSyD-mock-gemini-key-eczane-9942',
    byokProvider: 'gemini',
    ragSimilarityThreshold: 0.82,
    silenceTimeoutSec: 1.8,
    vadSensitivity: 'high',
  },
  jet_kargo: {
    agentName: 'Can (Kargo Takip Asistanı)',
    voiceModel: 'gemini-live-fenrir-clear',
    provider: 'gemini',
    tone: 'fast_efficient',
    systemPrompt: `Sen Jet Kargo Express'in hızlı ve çözüm odaklı AI asistanı Can'sın.
Arayan müşteriden 12 haneli takip numarasını veya telefon numarasını al.
Kargo durumu için hemen track_shipment MCP aracını çağır.
Kurye henüz dağıtıma çıkmadıysa veya teslimat başarısız olduysa doğrudan şubeye aktarma seçeneği sun.`,
    fillerPhrases: [
      'Takip numaranızı hemen sorguluyorum...',
      'Kurye dağıtım rotasını kontrol ediyorum...',
      'Bir saniye merkez sistemimize bakıyorum...',
    ],
    byokKey: 'sk-proj-mock-openai-key-jetkargo-8821',
    byokProvider: 'openai',
    ragSimilarityThreshold: 0.78,
    silenceTimeoutSec: 1.5,
    vadSensitivity: 'medium',
  },
};

export const initialMcpServers: Record<string, McpServerConfig[]> = {
  eczane_hayat: [
    {
      id: 'mcp_pharmacy_1',
      name: 'Eczane İlaç & Nöbet Entegrasyon Sunucusu',
      url: 'https://api.hayateczanesi.com/mcp/v1',
      authToken: 'Bearer mcp_sec_token_pharma_2026',
      status: 'connected',
      lastPingMs: 24,
      tools: [
        {
          name: 'check_medicine_stock',
          description: 'Verilen ilaç adının depodaki ve raftaki kutu adetini ve reçete türünü sorgular.',
          inputSchema: { medicine_name: 'string', dosage: 'string (optional)' },
          enabled: true,
        },
        {
          name: 'get_duty_pharmacy_info',
          description: 'Bugünkü nöbet durumunu, adresini ve nöbetçi eczacı telefonunu döner.',
          inputSchema: { date: 'string (YYYY-MM-DD)' },
          enabled: true,
        },
        {
          name: 'reserve_item_for_pickup',
          description: 'Müşteri adına ilacı 3 saat boyunca tezgaha rezerve eder.',
          inputSchema: { patient_phone: 'string', medicine_name: 'string' },
          enabled: true,
        },
      ],
    },
  ],
  jet_kargo: [
    {
      id: 'mcp_kargo_1',
      name: 'Jet Kargo ERP & Barkod Takip MCP',
      url: 'https://erp.jetkargo.com.tr/mcp-gateway',
      authToken: 'Bearer jet_erp_api_auth_live_99',
      status: 'connected',
      lastPingMs: 18,
      tools: [
        {
          name: 'track_shipment',
          description: '12 haneli takip koduyla paket konumunu ve tahmini teslim saatini döner.',
          inputSchema: { tracking_number: 'string' },
          enabled: true,
        },
        {
          name: 'reschedule_delivery',
          description: 'Teslimat gününü veya komşuya bırakma tercihini günceller.',
          inputSchema: { tracking_number: 'string', new_date: 'string', note: 'string' },
          enabled: true,
        },
      ],
    },
  ],
};

export const initialFaqs: Record<string, FaqItem[]> = {
  eczane_hayat: [
    {
      id: 'faq_1',
      question: 'Çalışma ve mesai saatleriniz nedir?',
      answer: 'Hafta içi 08:30 - 19:00, Cumartesi 09:00 - 18:00 arası açığız. Pazar günleri ve resmi tatillerde nöbet çizelgemize göre hizmet vermekteyiz.',
      category: 'Genel Bilgi',
      lastUpdated: '2026-02-14',
    },
    {
      id: 'faq_2',
      question: 'Eve ilaç veya medikal malzeme teslimatı yapıyor musunuz?',
      answer: 'Evet, Kadıköy ve Ataşehir sınırları içerisindeki adreslere 2 saat içinde kuryemiz ile teslimat yapıyoruz. Reçeteli ilaçlar için SMS ile reçete kodu gerekmektedir.',
      category: 'Kurye Hizmeti',
      lastUpdated: '2026-03-01',
    },
    {
      id: 'faq_3',
      question: 'SGK ve özel sağlık sigortası anlaşmanız var mı?',
      answer: 'Tüm SGK provizyon sistemleri ile birlikte Acıbadem Sigorta, Allianz, Mapfre ve Anadolu Sigorta anlaşmamız mevcuttur.',
      category: 'Sigorta & Ödeme',
      lastUpdated: '2026-01-20',
    },
  ],
  jet_kargo: [
    {
      id: 'faq_kargo_1',
      question: 'Kargom bugün saat kaça kadar gelir?',
      answer: 'Standart dağıtım saatlerimiz 09:00 - 18:30 arasındadır. Canlı kurye konumunu SMS ile gelen linkten izleyebilirsiniz.',
      category: 'Teslimat',
      lastUpdated: '2026-02-10',
    },
  ],
};

export const initialCdrs: CdrRecord[] = [
  {
    id: 'cdr_9921',
    callId: 'uuid-call-9921-884-ecza',
    tenantId: 'eczane_hayat',
    caller: '+90 532 987 6543',
    did: '+90 850 111 0001',
    startTime: '2026-10-02 08:42:10',
    durationSeconds: 94,
    cost: 0.78,
    currency: 'TRY',
    resolutionStatus: 'ai_resolved',
    agentPersona: 'Ayşe (Eczacı Asistanı)',
    mcpCallsCount: 2,
    summary: 'Müşteri Parol ve Augmentin stok sordu. AI stok MCP sorgulayarak rafta mevcut olduğunu belirtti ve tezgaha rezerve etti.',
    mosScore: 4.4,
  },
  {
    id: 'cdr_9922',
    callId: 'uuid-call-9922-885-ecza',
    tenantId: 'eczane_hayat',
    caller: '+90 544 333 2211',
    did: '+90 850 111 0001',
    startTime: '2026-10-02 08:50:24',
    durationSeconds: 142,
    cost: 1.18,
    currency: 'TRY',
    resolutionStatus: 'transferred_agent',
    agentPersona: 'Ayşe (Eczacı Asistanı)',
    mcpCallsCount: 1,
    summary: 'Hasta özel doz ayarlaması ve çocuk şurubu yan etkisi sordu. AI tıbbi tavsiye veremeyeceği için çağrıyı 101 Dahiliye (Eczacı Mehmet Bey) aktardı.',
    mosScore: 4.5,
  },
  {
    id: 'cdr_9923',
    callId: 'uuid-call-9923-886-ecza',
    tenantId: 'eczane_hayat',
    caller: '+90 530 111 9988',
    did: '+90 216 450 1234',
    startTime: '2026-10-02 09:05:00',
    durationSeconds: 45,
    cost: 0.38,
    currency: 'TRY',
    resolutionStatus: 'ai_resolved',
    agentPersona: 'Ayşe (Eczacı Asistanı)',
    mcpCallsCount: 1,
    summary: 'Arayan kişi bu gece nöbetçi olup olmadıklarını sordu. AI nöbet takvimini sorgulayıp bu gece açık olduklarını teyit etti.',
    mosScore: 4.6,
  },
  {
    id: 'cdr_9924',
    callId: 'uuid-call-9924-887-jet',
    tenantId: 'jet_kargo',
    caller: '+90 555 777 8899',
    did: '+90 850 222 3456',
    startTime: '2026-10-02 09:12:15',
    durationSeconds: 68,
    cost: 0.56,
    currency: 'TRY',
    resolutionStatus: 'ai_resolved',
    agentPersona: 'Can (Kargo Takip Asistanı)',
    mcpCallsCount: 1,
    summary: 'Takip numarası 982187364123 sorgulandı. Paket Üsküdar şubesinde dağıtımda olduğu bilgisi verildi.',
    mosScore: 4.3,
  },
  {
    id: 'cdr_9925',
    callId: 'uuid-call-9925-888-ecza',
    tenantId: 'eczane_hayat',
    caller: '+90 535 222 3344',
    did: '+90 850 111 0001',
    startTime: '2026-10-02 09:20:00',
    durationSeconds: 22,
    cost: 0.18,
    currency: 'TRY',
    resolutionStatus: 'user_hangup',
    agentPersona: 'Ayşe (Eczacı Asistanı)',
    mcpCallsCount: 0,
    summary: 'Karşılama anonsu sonrası arayan kişi telefonu kapattı.',
    mosScore: 4.1,
  },
];

export const sampleLiveTranscript: LiveTranscriptEntry[] = [
  {
    id: 'tr_1',
    timestamp: '09:30:02',
    sender: 'system',
    text: 'SIP INVITE alındı (DID: +90 850 111 0001) | Diameter Ro CCR-Init başlatıldı (Kredi: 840.50 TRY OK)',
  },
  {
    id: 'tr_2',
    timestamp: '09:30:04',
    sender: 'ai',
    text: 'Hayat Eczanesi\'ne hoş geldiniz! Ben sanal asistanınız Ayşe. Size nasıl yardımcı olabilirim?',
    sentiment: 'positive',
  },
  {
    id: 'tr_3',
    timestamp: '09:30:08',
    sender: 'caller',
    text: 'Merhaba Ayşe Hanım, elinizde Parol Plus ve Ventolin inhaler var mı acaba?',
    sentiment: 'neutral',
  },
  {
    id: 'tr_4',
    timestamp: '09:30:10',
    sender: 'ai',
    text: 'Hemen stoklarımızı kontrol ediyorum efendim, bir saniye bekleteceğim...',
    mcpAction: {
      tool: 'check_medicine_stock',
      input: '{"medicine_name": "Parol Plus, Ventolin inhaler"}',
      output: '{"Parol Plus": {"stock": 14, "available": true}, "Ventolin": {"stock": 3, "available": true}}',
    },
    sentiment: 'positive',
  },
  {
    id: 'tr_5',
    timestamp: '09:30:13',
    sender: 'ai',
    text: 'Kontrol ettim, hem Parol Plus hem de Ventolin inhaler şu an stoklarımızda mevcut. Sizin için tezgaha rezerve etmemi ister misiniz?',
    sentiment: 'positive',
  },
  {
    id: 'tr_6',
    timestamp: '09:30:18',
    sender: 'caller',
    text: 'Harika olur, yaklaşık yarım saate gelip alacağım. Çok teşekkürler!',
    sentiment: 'positive',
  },
];
